### ISSUE TITLE
There seems to be a problem with the bluetooth module as well

### ISSUE THREAD

**Issue by LuckyFishGeek** [ElectronicCats/flipper-shields#4]
Firmware version:13.5
flipper zero MARAUDER version:6.5

![6](https://github.com/ElectronicCats/flipper-shields/assets/29472751/73a9046b-469b-4290-a46c-a2cb5dfe686c)

**Comment by xpeqex** [comment]
Hi @LuckyFishGeek 

Thank you for contracting us.

The reason you are facing this issue is that the firmware you are running does not have the BL enabled. Please upgrade the firmware following these steps: [Update the ESP32-S3 Marauder firmware](https://github.com/ElectronicCats/flipper-shields/wiki/Flipper-Add%E2%80%90On:-Marauder-Spoof#update-the-esp32-s3-marauder-firmware). The links to the files are now updated to use our firmware file, in any case you can download the corresponding for 0x10000 file for it from this [link](https://github.com/ElectronicCats/ESP32Marauder/blob/master/esp32_marauder/esp32_marauder.ino.esp32s3.bin).

I am currently running this Marauder script, and it is working, so annoying to be honest haha.

Let me know if you have any other questions.
Pd: I noticed for your reactions on the other issue 😶‍🌫️

**Comment by avipars** [comment]
Any chance of getting it to support the official v1.2 firmware?

**Comment by xpeqex** [comment]
@avipars 
Thanks for reporting this, we will take a look at it and work on getting the Add-On to support the newer firmware.

We will keep you posted on the new issue you open.
